import type { ReactNode } from 'react'
import { cloneElement, isValidElement, useId } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { AlertCircle, ArrowLeft, Check, ChevronLeft, ChevronRight, Database, LoaderCircle, Search, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ApiError } from '../api/client'

export const number = (value: unknown) => value == null ? '—' : new Intl.NumberFormat('es-CO', { maximumFractionDigits: 2 }).format(Number(value))
export const date = (value: unknown, time = true) => !value ? '—' : new Date(String(value)).toLocaleString('es-CO', { day: '2-digit', month: 'short', year: 'numeric', ...(time ? { hour: '2-digit', minute: '2-digit' } as const : {}) })
const labels: Record<string, string> = { ACTIVE: 'Activo', INACTIVE: 'Inactivo', READY: 'Disponible', COMPLETED: 'Completada', SUCCESS: 'Completada', SUCCEEDED: 'Completada', FAILED: 'Falló', ERROR: 'Error', PASS: 'Cumple', FAIL: 'Incumple', WARN: 'Alerta', WARNING: 'Alerta', QUEUED: 'En cola', RUNNING: 'En curso', CANCELLED: 'Cancelada', OPEN: 'Abierta', IN_PROGRESS: 'En gestión', INVESTIGATING: 'En investigación', RESOLVED: 'Resuelta', CLOSED: 'Cerrada', HIGH: 'Alta', MEDIUM: 'Media', LOW: 'Baja', CRITICAL: 'Crítica', APPROVED: 'Aprobado', APPROVED_WITH_WARNINGS: 'Con observaciones', REJECTED: 'Rechazado', MATCH: 'Coincide', VALUE_MISMATCH: 'Diferencia de valor', FIELD_MISMATCH: 'Diferencia de campo', SOURCE_ONLY: 'Solo en origen', TARGET_ONLY: 'Solo en destino', DUPLICATE_SOURCE: 'Duplicado en origen', DUPLICATE_TARGET: 'Duplicado en destino', DUPLICATE_KEY: 'Clave duplicada', INVALID_KEY: 'Clave inválida', VALID: 'Válido', intake: 'Intake', recon: 'ReconOps', sentinel: 'Sentinel', ADMIN: 'Administrador', Administrator: 'Administrador', GENERATED_DEMO: 'Datos de demostración', UPLOAD: 'Archivo cargado' }
Object.assign(labels, { ORIGINAL_UPLOAD: 'Archivo original subido', CANONICAL_PARQUET: 'Parquet canónico', INTAKE_ACCEPTED: 'Datos aceptados por Intake', IDENTIFIER: 'Identificador', REQUIRED: 'Dato obligatorio', UNIQUE: 'Valor único', NUMERIC: 'Valor numérico', POSITIVE: 'Valor positivo', RANGE: 'Rango permitido', ALLOWED_VALUES: 'Valor permitido', REGEX: 'Patrón de texto', DATE_RULE: 'Regla de fecha', EXACT_COMPARE: 'Igualdad exacta', EXACT_MATCH: 'Tolerancia numérica (histórica)', NUMERIC_TOLERANCE: 'Tolerancia numérica', DATE_TOLERANCE: 'Tolerancia de fecha', HEALTHY: 'Saludable', ALERT: 'Alerta', WITH_FINDINGS: 'Con hallazgos', CONFORME: 'Conforme', INVALID: 'Registro inválido', WAITING_EXTERNAL: 'Espera externa', ACCEPTED: 'Aceptada', FALSE_POSITIVE: 'Falso positivo', PUBLISHED: 'Publicada', INTAKE_OUTPUT: 'Salida de Intake', STRING: 'Texto', INTEGER: 'Entero', DECIMAL: 'Decimal', BOOLEAN: 'Booleano', DATE: 'Fecha', DATETIME: 'Fecha y hora', ONLINE: 'En línea', OFFLINE: 'Desconectado', AVAILABLE: 'Disponible', UNAVAILABLE: 'No disponible', ok: 'Operativo', local: 'Local', running: 'En ejecución', idle: 'En espera' })
Object.assign(labels, { ASSIGNED: 'Asignada', REOPENED: 'Reabierta', PENDING_VALIDATION: 'Pendiente de validación', DISCARDED: 'Descartada', NOT_APPLICABLE: 'No aplica', NOT_REQUESTED: 'Sin validar', NO_LATER_RUN: 'Sin ejecución posterior', VALIDATED: 'Validada', BLOCKED: 'Bloqueada', LEGACY_UNVERIFIED: 'Cierre histórico sin validar', ADMINISTRATIVE_CLOSURE: 'Cierre administrativo' })
Object.assign(labels, { FAILED_PRECONDITION: 'Precondición no cumplida', POSTGRESQL: 'PostgreSQL', SQLSERVER: 'SQL Server', SOURCE_SNAPSHOT: 'Snapshot de fuente externa' })
export function label(value: unknown) { return labels[String(value)] || String(value ?? '—').replaceAll('_', ' ') }
export function Badge({ value, children }: { value?: unknown; children?: ReactNode }) {
  const v = String(value || '').toUpperCase()
  const tone = ['ACTIVE', 'READY', 'COMPLETED', 'SUCCESS', 'SUCCEEDED', 'PASS', 'MATCH', 'RESOLVED', 'CLOSED', 'APPROVED', 'VALID', 'VALIDATED', 'LOW', 'HEALTHY', 'CONFORME', 'ACCEPTED', 'FALSE_POSITIVE', 'PUBLISHED', 'ONLINE', 'AVAILABLE', 'OK'].includes(v) ? 'green' : ['FAILED', 'FAILED_PRECONDITION', 'ERROR', 'FAIL', 'REJECTED', 'CRITICAL', 'HIGH', 'VALUE_MISMATCH', 'FIELD_MISMATCH', 'INVALID_KEY', 'INVALID', 'OFFLINE', 'UNAVAILABLE'].includes(v) ? 'red' : ['OPEN', 'WARNING', 'WARN', 'MEDIUM', 'APPROVED_WITH_WARNINGS', 'DUPLICATE_SOURCE', 'DUPLICATE_TARGET', 'DUPLICATE_KEY', 'SOURCE_ONLY', 'TARGET_ONLY', 'ALERT', 'WITH_FINDINGS', 'WAITING_EXTERNAL', 'PENDING_VALIDATION', 'NOT_REQUESTED', 'NO_LATER_RUN'].includes(v) ? 'amber' : 'blue'
  return <span className={`badge ${tone}`}><span className="badge-dot"/>{children || label(value)}</span>
}
export function Loading({ text = 'Cargando información…' }: { text?: string }) { return <div className="loading-state" role="status"><LoaderCircle className="spin" size={23}/><span>{text}</span><div className="skeleton-lines"><i/><i/><i/></div></div> }
export function ErrorState({ error, retry }: { error: unknown; retry?: () => void }) { return <div className="error-state" role="alert"><AlertCircle size={22}/><div><strong>No pudimos completar la operación</strong><p>{error instanceof Error ? error.message : String(error)}</p>{error instanceof ApiError && error.requestId && <small>Referencia: {error.requestId}</small>}{retry && <button className="button secondary small" onClick={retry}>Volver a intentar</button>}</div></div> }
export function Empty({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="empty-state"><div className="empty-icon"><Database size={25}/></div><h3>{title}</h3><p>{description}</p>{action}</div> }
export function PageHeading({ eyebrow, title, description, action, back }: { eyebrow?: string; title: string; description: string; action?: ReactNode; back?: string }) { return <div className="page-heading"><div>{back && <Link to={back} className="back-link"><ArrowLeft size={14}/> Volver</Link>}{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div>{action && <div className="heading-actions">{action}</div>}</div> }
export function Modal({ open, onOpenChange, title, description, children, wide = false }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; description?: string; children: ReactNode; wide?: boolean }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className={`modal ${wide ? 'wide' : ''}`}><div className="modal-heading"><div><Dialog.Title>{title}</Dialog.Title>{description && <Dialog.Description>{description}</Dialog.Description>}</div><Dialog.Close className="icon-button" aria-label="Cerrar ventana"><X size={20}/></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root> }
export function Field({ label: title, hint, children }: { label: string; hint?: string; children: ReactNode }) {
  const generatedId = useId()
  const control = isValidElement<{ id?: string; 'aria-describedby'?: string }>(children) ? children : null
  const id = control?.props.id || generatedId
  return <div className="field"><label htmlFor={id}>{title}</label>{control ? cloneElement(control, { id, 'aria-describedby': [control.props['aria-describedby'], hint ? `${id}-hint` : ''].filter(Boolean).join(' ') || undefined }) : children}{hint && <small id={`${id}-hint`}>{hint}</small>}</div>
}
export function SearchBox({ value, onChange, placeholder = 'Buscar…' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="search-box"><Search size={17}/><input aria-label={placeholder} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}/>{value && <button className="icon-button" aria-label="Limpiar búsqueda" onClick={() => onChange('')}><X size={14}/></button>}</div> }
export function Pagination({ offset, total, limit, onChange }: { offset: number; total: number; limit: number; onChange: (value: number) => void }) { return <div className="pagination"><span>{total ? `${number(offset + 1)}–${number(Math.min(offset + limit, total))} de ${number(total)}` : '0 resultados'}</span><div><button className="icon-button" disabled={!offset} aria-label="Página anterior" onClick={() => onChange(Math.max(0, offset - limit))}><ChevronLeft size={17}/></button><button className="icon-button" disabled={offset + limit >= total} aria-label="Página siguiente" onClick={() => onChange(offset + limit)}><ChevronRight size={17}/></button></div></div> }
export function Notice({ children, success = false }: { children: ReactNode; success?: boolean }) { return <div className={`notice ${success ? 'success' : ''}`} role="status">{success ? <Check size={17}/> : <AlertCircle size={17}/>}<span>{children}</span></div> }
