import { useQuery } from '@tanstack/react-query'
import { api, type Collection } from '../../api/client'
import { Badge, date, Empty, ErrorState, Loading, Notice } from '../../components/ui'

export function NotificationsPanel() {
  const status = useQuery({ queryKey: ['notification-status'], queryFn: () => api('/notifications/status') })
  const deliveries = useQuery({ queryKey: ['notification-deliveries'], queryFn: () => api<Collection>('/notifications/deliveries') })
  return <section className="panel"><div className="panel-heading"><div><h2>Notificaciones por correo</h2><p>Estado de la integración y metadatos de entrega de credenciales.</p></div><button className="button secondary" onClick={() => { status.refetch(); deliveries.refetch() }}>Actualizar envíos</button></div>{status.isPending ? <Loading/> : status.error ? <ErrorState error={status.error}/> : <Notice success={Boolean(status.data?.enabled && status.data?.configured)}>{status.data?.enabled && status.data?.configured ? `Integración SMTP configurada · ${status.data.security}` : 'Integración SMTP no configurada o deshabilitada. Configura el servicio en el entorno y regenera las credenciales desde Usuarios locales.'}</Notice>}{status.data?.from_address && <p className="muted" style={{ padding: '0 24px 20px' }}>Remitente: {status.data.from_name} &lt;{status.data.from_address}&gt;</p>}{deliveries.isPending ? <Loading/> : deliveries.error ? <ErrorState error={deliveries.error} retry={() => deliveries.refetch()}/> : !deliveries.data?.items.length ? <Empty title="Sin envíos registrados" description="Los intentos de envío aparecerán aquí."/> : <div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Destinatario</th><th>Evento</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>{deliveries.data.items.map(item => <tr key={item.id}><td>{date(item.created_at)}</td><td>{item.recipient_email_snapshot}</td><td>{item.event_type}</td><td><Badge value={item.status}/></td><td>{item.error_code || (item.sent_at ? `Enviado ${date(item.sent_at)}` : '—')}</td></tr>)}</tbody></table></div>}</section>
}
