import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ChevronDown, ChevronRight, Database, Pencil, Plus } from 'lucide-react'
import { api, post } from '../../api/client'
import type { Collection, RecordData } from '../../api/client'
import { usePermission } from '../../app/session'
import { Badge, date, Empty, ErrorState, Field, label, Loading, Modal, Notice, number, PageHeading, Pagination, SearchBox } from '../../components/ui'
import { ClassificationField } from './ClassificationField'
import type { Classification, GovernanceEntity } from './ClassificationField'
import './catalog.css'

const limit = 25
const resourceNames: Record<string, string> = { DATASET: 'Datasets', INTAKE: 'Data Intake', RECON: 'ReconOps', SENTINEL: 'Sentinel', DELIVERY: 'Data Delivery', REPORT: 'Reportes' }
type TreeNode = { id: string; label: string; type: string; count: number; has_children: boolean }
type TreeScope = { domain_id?: string; macro_domain_id?: string; pending?: string }
type DatasetSection = { dataset: RecordData; governance: RecordData; items: RecordData[]; total: number; eligibility?: RecordData; version_id?: string; dataset_terms?: RecordData[] }
const sections = [['summary', 'Resumen y gobierno'], ['columns', 'Columnas y glosario'], ['versions', 'Versiones'], ['quality', 'Calidad y contratos'], ['lineage', 'Linaje'], ['history', 'Historial']]

function TreeBranch({ node, scope, onSelect }: { node: TreeNode; scope: TreeScope; onSelect: (node: TreeNode, scope: TreeScope) => void }) {
  const [expanded, setExpanded] = useState(false), expandable = node.has_children && node.type !== 'resource_type'
  const nextScope = node.type === 'domain' ? { ...scope, domain_id: node.id } : node.type === 'macro_domain' ? { macro_domain_id: node.id } : node.type === 'pending' ? { pending: 'true' } : scope
  return <li><button aria-expanded={expandable ? expanded : undefined} onClick={() => { onSelect(node, nextScope); if (expandable) setExpanded(!expanded) }}>{expandable ? expanded ? <ChevronDown size={14}/> : <ChevronRight size={14}/> : <Database size={14}/>}<span>{node.label}</span><span className="tree-count">{number(node.count)}</span></button>{expanded && expandable && <TreeNodes parent={node} scope={nextScope} onSelect={onSelect}/>}</li>
}

function TreeNodes({ parent, scope = {}, onSelect }: { parent?: TreeNode; scope?: TreeScope; onSelect: (node: TreeNode, scope: TreeScope) => void }) {
  const [offset, setOffset] = useState(0)
  const query = new URLSearchParams({ offset: String(offset), limit: String(limit) }); if (parent) { query.set('parent_type', parent.type); query.set('parent_id', parent.id) }
  const nodes = useQuery({ queryKey: ['catalog-tree', query.toString()], queryFn: () => api<{ items: TreeNode[]; total: number }>(`/catalog/tree?${query}`) })
  return <>{nodes.isPending ? <Loading text="Cargando rama…"/> : nodes.error ? <ErrorState error={nodes.error} retry={() => { void nodes.refetch() }}/> : <ul>{nodes.data?.items.map(node => <TreeBranch key={`${node.type}:${node.id}`} node={node} scope={scope} onSelect={onSelect}/>)}</ul>}{(nodes.data?.total || 0) > limit && <Pagination offset={offset} total={nodes.data?.total || 0} limit={limit} onChange={setOffset}/>}</>
}

function CatalogTree() {
  const navigate = useNavigate()
  function select(node: TreeNode, scope: TreeScope) {
    const next = new URLSearchParams(scope)
    if (node.type === 'resource_type') next.set('resource_type', node.id)
    navigate(`/catalog?${next}`)
  }
  return <aside className="panel catalog-tree" aria-label="Árbol de catálogo"><h2>Catálogo de recursos</h2><Link to="/catalog">Todos los datasets</Link><TreeNodes onSelect={select}/><Link to="/catalog/admin">Administración y glosario</Link></aside>
}

export function CatalogResources() {
  const [params, setParams] = useSearchParams()
  const offset = Math.max(0, Number(params.get('offset')) || 0)
  const query = new URLSearchParams(params); query.set('limit', String(limit)); query.set('offset', String(offset)); if (params.get('unclassified')) query.set('pending', 'true')
  const resources = useQuery({ queryKey: ['catalog-resources', query.toString()], queryFn: () => api<Collection>(`/catalog/resources?${query}`) })
  function filter(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.delete('offset'); setParams(next, { replace: true }) }
  return <section className="panel"><div className="catalog-filters"><SearchBox value={params.get('search') || ''} onChange={value => filter('search', value)} placeholder="Buscar recursos del catálogo…"/><select aria-label="Tipo de recurso" value={params.get('resource_type') || ''} onChange={event => filter('resource_type', event.target.value)}><option value="">Datasets</option>{Object.entries(resourceNames).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select><select aria-label="Estado del recurso" value={params.get('status') || ''} onChange={event => filter('status', event.target.value)}><option value="">Todos los estados</option>{['ACTIVE', 'READY', 'APPROVED', 'BLOCKED'].map(value => <option key={value} value={value}>{label(value)}</option>)}</select><input aria-label="Filtrar por responsable" placeholder="Identidad del responsable" value={params.get('responsible') || ''} onChange={event => filter('responsible', event.target.value)}/></div>
    {(params.get('unclassified') || params.get('pending')) && <Notice>Activos con clasificación incompleta o inactiva. Sus versiones y evidencias se conservan.</Notice>}
    {resources.isPending ? <Loading/> : resources.error ? <ErrorState error={resources.error} retry={() => { void resources.refetch() }}/> : !resources.data?.items.length ? <Empty title="No hay recursos con estos filtros" description="Prueba otra búsqueda, selecciona otra rama o completa la clasificación de tus datasets."/> : <div className="table-scroll"><table><thead><tr><th>Recurso</th><th>Tipo</th><th>Clasificación vigente</th><th>Estado</th><th/></tr></thead><tbody>{resources.data.items.map(item => <tr key={`${item.resource_type}:${item.id}`}><td><Link className="table-primary" to={item.resource_type === 'DATASET' ? `/catalog/datasets/${item.dataset_id || item.id}` : item.href || `/catalog/datasets/${item.dataset_id}`}>{item.name}</Link><small className="table-subtitle">{item.governance?.business_owner?.name || item.owner}</small></td><td>{resourceNames[item.resource_type] || label(item.resource_type)}</td><td>{item.governance?.macro_domain?.name || item.governance?.macro_domain_name || 'Sin macrodominio'} / {item.governance?.domain?.name || item.governance?.domain_name || 'Sin dominio'}</td><td><Badge value={item.status}/>{item.eligibility && <small className="table-subtitle">{item.eligibility.eligible ? 'Habilitado para Reportes' : 'Reportes: no habilitado'}</small>}</td><td><Link className="text-link" to={item.resource_type === 'DATASET' ? `/catalog/datasets/${item.dataset_id || item.id}` : item.href || `/catalog/datasets/${item.dataset_id}`}>Inspeccionar</Link></td></tr>)}</tbody></table></div>}
    <Pagination offset={offset} total={resources.data?.total || 0} limit={limit} onChange={value => { const next = new URLSearchParams(params); next.set('offset', String(value)); setParams(next) }}/>
  </section>
}

function GovernanceEditor({ dataset, governance, onClose }: { dataset: RecordData; governance: RecordData; onClose: () => void }) {
  const cache = useQueryClient()
  const [classification, setClassification] = useState<Classification>({ macro_domain_id: governance.macro_domain_id || dataset.macro_domain_id || null, domain_id: governance.domain_id || dataset.domain_id || null })
  const [form, setForm] = useState({ description: governance.description || dataset.description || '', business_owner_id: governance.business_owner_id || '', steward_id: governance.steward_id || '', technical_custodian_id: governance.technical_custodian_id || '', information_classification: governance.information_classification || 'UNKNOWN', criticality: governance.criticality || dataset.criticality || 'MEDIUM' })
  const save = useMutation({ mutationFn: () => api(`/datasets/${dataset.id}/governance`, { method: 'PATCH', body: JSON.stringify({ expected_version: governance.version ?? dataset.governance_version ?? 1, ...classification, ...form, business_owner_id: form.business_owner_id || null, steward_id: form.steward_id || null, technical_custodian_id: form.technical_custodian_id || null }) }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['catalog-dataset', dataset.id] }); void cache.invalidateQueries({ queryKey: ['catalog-resources'] }); void cache.invalidateQueries({ queryKey: ['catalog-tree'] }); void cache.invalidateQueries({ queryKey: ['datasets'] }); onClose() } })
  const canReadUsers = usePermission('users:read')
  const users = useQuery({ queryKey: ['users', 'governance-selection'], queryFn: () => api<Collection>('/users'), enabled: canReadUsers })
  return <Modal open onOpenChange={open => { if (!open && !save.isPending) onClose() }} title="Editar gobierno vigente" description="La documentación y clasificación no cambian las versiones ni las aprobaciones históricas." wide><form className="form-stack" onSubmit={event => { event.preventDefault(); save.mutate() }}>
    <ClassificationField value={classification} onChange={setClassification} legacyValue={dataset.domain} disabled={save.isPending}/><Field label="Descripción funcional"><textarea value={form.description} maxLength={2000} onChange={event => setForm({ ...form, description: event.target.value })}/></Field>
    <div className="form-grid">{([['business_owner_id', 'Responsable de negocio'], ['steward_id', 'Gestor del dato'], ['technical_custodian_id', 'Custodio técnico']] as const).map(([key, title]) => <Field key={key} label={title} hint="La asignación no concede permisos. Se conserva la identidad histórica.">{canReadUsers ? <select value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })}><option value="">Sin asignar</option>{form[key] && !(users.data?.items || []).some(user => user.id === form[key]) && <option value={form[key]}>Identidad heredada o inactiva · {form[key]}</option>}{(users.data?.items || []).map(user => <option key={user.id} value={user.id}>{user.name} {user.active === false || user.status === 'INACTIVE' ? '(inactiva)' : ''}</option>)}</select> : <input value={form[key]} placeholder="Identificador de usuario" onChange={event => setForm({ ...form, [key]: event.target.value })}/>}</Field>)}
      <Field label="Clasificación de información"><select value={form.information_classification} onChange={event => setForm({ ...form, information_classification: event.target.value })}>{['UNKNOWN', 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'].map(value => <option key={value} value={value}>{value === 'UNKNOWN' ? 'Sin determinar' : label(value)}</option>)}</select></Field><Field label="Criticidad"><select value={form.criticality} onChange={event => setForm({ ...form, criticality: event.target.value })}>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map(value => <option key={value} value={value}>{label(value)}</option>)}</select></Field></div>{save.error && <ErrorState error={save.error}/>}<div className="modal-footer"><button type="button" className="button secondary" disabled={save.isPending} onClick={onClose}>Cancelar</button><button className="button primary" disabled={save.isPending}>{save.isPending ? 'Guardando…' : 'Guardar gobierno'}</button></div>
  </form></Modal>
}

function ColumnEditor({ datasetId, column, versionId, onClose }: { datasetId: string; column: RecordData; versionId: string; onClose: () => void }) {
  const cache = useQueryClient(), canReadGlossary = usePermission('glossary:read'), [description, setDescription] = useState(column.description || column.documentation?.description || ''), [terms, setTerms] = useState<string[]>(column.term_ids || column.documentation?.term_ids || (column.terms || []).map((term: RecordData) => term.id))
  const glossary = useQuery({ queryKey: ['governance-glossary', 'column'], queryFn: () => api<Collection>('/governance/glossary?active=true&limit=200'), enabled: canReadGlossary })
  const availableTerms = Object.values(Object.fromEntries([...(column.terms || []), ...terms.filter(id => !(column.terms || []).some((term: RecordData) => term.id === id)).map(id => ({ id, name: id })), ...(glossary.data?.items || [])].map(term => [term.id, term]))) as RecordData[]
  const save = useMutation({ mutationFn: () => api(`/catalog/datasets/${datasetId}/columns`, { method: 'PATCH', body: JSON.stringify({ version_id: versionId, column_name: column.name || column.column_name, description, term_ids: terms, expected_version: column.documentation?.version || column.documentation_version || 0 }) }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['catalog-dataset', datasetId] }); onClose() } })
  return <Modal open onOpenChange={open => { if (!open && !save.isPending) onClose() }} title={`Documentar ${column.name || column.column_name}`} description="La documentación queda vinculada a esta versión y esquema. El tipo físico se conserva."><form className="form-stack" onSubmit={event => { event.preventDefault(); save.mutate() }}><Field label="Descripción funcional de la columna"><textarea value={description} onChange={event => setDescription(event.target.value)}/></Field><fieldset><legend>Términos del glosario</legend>{!canReadGlossary ? <Notice>Tu rol puede editar la descripción. Las asociaciones existentes se conservan; consultar términos requiere permiso de glosario.</Notice> : glossary.isPending ? <Loading/> : glossary.error ? <ErrorState error={glossary.error} retry={() => { void glossary.refetch() }}/> : availableTerms.map(term => <label className="checkbox-row" key={term.id}><input type="checkbox" checked={terms.includes(term.id)} onChange={event => setTerms(event.target.checked ? [...terms, term.id] : terms.filter(id => id !== term.id))}/>{term.name}{term.active === false && ' (inactivo; asociación histórica)'}</label>)}</fieldset>{save.error && <ErrorState error={save.error}/>}<div className="modal-footer"><button type="button" className="button secondary" disabled={save.isPending} onClick={onClose}>Cancelar</button><button className="button primary" disabled={save.isPending}>Guardar documentación</button></div></form></Modal>
}

function DatasetGlossary({ datasetId, terms }: { datasetId: string; terms: RecordData[] }) {
  const cache = useQueryClient(), canManage = usePermission('glossary:manage'), canRead = usePermission('glossary:read')
  const [selected, setSelected] = useState(''), [removing, setRemoving] = useState<RecordData | null>(null)
  const available = useQuery({ queryKey: ['governance-glossary', 'dataset'], queryFn: () => api<Collection>('/governance/glossary?active=true&limit=200'), enabled: canManage && canRead })
  const save = useMutation({ mutationFn: () => post(`/catalog/datasets/${datasetId}/terms`, { term_id: selected }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['catalog-dataset', datasetId] }); setSelected('') } })
  const remove = useMutation({ mutationFn: () => api(`/catalog/glossary-associations/${removing!.association_id}`, { method: 'DELETE' }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['catalog-dataset', datasetId] }); setRemoving(null) } })
  return <section className="report-context"><h3>Glosario del dataset</h3>{terms.length ? terms.map(term => <details key={term.association_id}><summary>{term.name} {term.active === false && '(término inactivo)'}</summary><p>{term.definition}</p>{canManage && <button className="text-button" onClick={() => { setRemoving(term); remove.reset() }}>Quitar asociación con {term.name}</button>}</details>) : <p className="muted">Sin términos asociados al dataset.</p>}{canManage && canRead && <div className="report-key-row"><Field label="Asociar término al dataset"><select value={selected} disabled={available.isPending || save.isPending} onChange={event => setSelected(event.target.value)}><option value="">Selecciona un término</option>{(available.data?.items || []).filter(term => !terms.some(current => current.id === term.id)).map(term => <option key={term.id} value={term.id}>{term.name}</option>)}</select></Field><button className="button secondary" disabled={!selected || save.isPending} onClick={() => save.mutate()}>Asociar término</button></div>}{available.error && <ErrorState error={available.error} retry={() => { void available.refetch() }}/>} {save.error && <ErrorState error={save.error}/>}<Modal open={!!removing} onOpenChange={open => { if (!open && !remove.isPending) setRemoving(null) }} title="Quitar asociación de glosario" description={`Confirma que deseas retirar «${removing?.name || ''}» de este dataset. El término compartido se conserva.`}>{remove.error && <ErrorState error={remove.error}/>}<div className="modal-footer"><button className="button secondary" disabled={remove.isPending} onClick={() => setRemoving(null)}>Cancelar</button><button className="button primary" disabled={remove.isPending} onClick={() => remove.mutate()}>Confirmar retirada</button></div></Modal></section>
}

function DatasetBlocks({ datasetId }: { datasetId: string }) {
  const cache = useQueryClient(), canManage = usePermission('blocks:manage')
  const [action, setAction] = useState<RecordData | null>(null), [reason, setReason] = useState(''), [scope, setScope] = useState('REPORT')
  const blocks = useQuery({ queryKey: ['catalog-blocks', datasetId], queryFn: () => api<Collection>(`/catalog/datasets/${datasetId}/blocks`) })
  const update = useMutation({ mutationFn: () => action?.id ? api(`/catalog/blocks/${action.id}`, { method: 'PATCH', body: JSON.stringify({ expected_version: action.version, active: false, reason: reason.trim() }) }) : post(`/catalog/datasets/${datasetId}/blocks`, { scope, reason: reason.trim() }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['catalog-blocks', datasetId] }); void cache.invalidateQueries({ queryKey: ['catalog-dataset', datasetId] }); setAction(null); setReason('') } })
  return <><div className="panel-heading"><div><h3>Bloqueos vigentes</h3><p>Su alcance no altera la aprobación histórica.</p></div>{canManage && <button className="button secondary small" onClick={() => { setAction({}); setReason(''); update.reset() }}>Bloquear uso</button>}</div>{blocks.error ? <ErrorState error={blocks.error} retry={() => { void blocks.refetch() }}/> : (blocks.data?.items || []).filter(item => item.active).map(block => <Notice key={block.id}>{label(block.scope)}: {block.reason} {block.inherited && '(heredado de una fuente)'} {canManage && !block.inherited && <button className="text-button" onClick={() => { setAction(block); setReason(''); update.reset() }}>Liberar bloqueo</button>}</Notice>)}
    <Modal open={!!action} onOpenChange={open => { if (!open && !update.isPending) setAction(null) }} title={action?.id ? 'Liberar bloqueo' : 'Bloquear uso del dataset'} description="Confirma el alcance y el motivo. Esta acción se registra en auditoría."><form className="form-stack" onSubmit={event => { event.preventDefault(); update.mutate() }}>{!action?.id && <Field label="Alcance"><select value={scope} onChange={event => setScope(event.target.value)}><option value="REPORT">Uso en Reportes</option><option value="CONTENT">Acceso al contenido y derivados</option></select></Field>}<Field label="Motivo"><textarea required minLength={3} value={reason} onChange={event => setReason(event.target.value)}/></Field>{update.error && <ErrorState error={update.error}/>}<div className="modal-footer"><button type="button" className="button secondary" onClick={() => setAction(null)} disabled={update.isPending}>Cancelar</button><button className="button primary" disabled={update.isPending || reason.trim().length < 3}>Confirmar {action?.id ? 'liberación' : 'bloqueo'}</button></div></form></Modal></>
}

export function CatalogDataset() {
  const { id } = useParams(), [params, setParams] = useSearchParams(), canEdit = usePermission('governance:write')
  const section = sections.some(([key]) => key === params.get('section')) ? params.get('section')! : 'summary', offset = Math.max(0, Number(params.get('offset')) || 0)
  const [editing, setEditing] = useState(false), [column, setColumn] = useState<RecordData | null>(null)
  const query = new URLSearchParams({ section, offset: String(offset), limit: String(limit) }); if (params.get('version_id')) query.set('version_id', params.get('version_id')!)
  const data = useQuery({ queryKey: ['catalog-dataset', id, query.toString()], queryFn: () => api<DatasetSection>(`/catalog/datasets/${id}?${query}`), placeholderData: (previous, previousQuery) => previousQuery?.queryKey[1] === id ? previous : undefined })
  const value = data.data, dataset = value?.dataset, governance = value?.governance || {}, eligibility = value?.eligibility || governance.eligibility || dataset?.eligibility || {}
  if (data.isPending) return <Loading text="Consultando ficha del dataset…"/>
  if (data.error) return <ErrorState error={data.error} retry={() => { void data.refetch() }}/>
  if (!dataset) return <Empty title="Dataset no disponible" description="No existe o tu rol no permite inspeccionarlo."/>
  return <section className="panel catalog-detail"><nav className="catalog-breadcrumb" aria-label="Ruta del recurso"><Link to="/catalog">Catálogo</Link><ChevronRight size={13}/><span>{governance.macro_domain?.name || governance.macro_domain_name || 'Pendientes de clasificación'}</span><ChevronRight size={13}/><span>{governance.domain?.name || governance.domain_name || 'Sin dominio'}</span><ChevronRight size={13}/><strong>{dataset.name}</strong></nav>
    <div className="panel-heading"><div><h2>{dataset.name}</h2><p>{dataset.description || 'Ficha de gobierno y evidencia verificable.'}</p></div><Link className="button secondary small" to={`/datasets/${id}`}>Abrir contenido</Link></div>
    <div className="tabs" role="tablist" aria-label="Secciones del dataset">{sections.map(([key, title]) => <button role="tab" id={`catalog-tab-${key}`} aria-controls="catalog-section" aria-selected={section === key} tabIndex={section === key ? 0 : -1} key={key} className={section === key ? 'active' : ''} onKeyDown={event => { const index = sections.findIndex(([value]) => value === key); const target = event.key === 'ArrowRight' ? (index + 1) % sections.length : event.key === 'ArrowLeft' ? (index + sections.length - 1) % sections.length : event.key === 'Home' ? 0 : event.key === 'End' ? sections.length - 1 : -1; if (target >= 0) { event.preventDefault(); document.getElementById(`catalog-tab-${sections[target][0]}`)?.focus(); const next = new URLSearchParams(params); next.set('section', sections[target][0]); next.delete('offset'); setParams(next) } }} onClick={() => { const next = new URLSearchParams(params); next.set('section', key); next.delete('offset'); setParams(next) }}>{title}</button>)}</div>
    <div role="tabpanel" id="catalog-section" aria-labelledby={`catalog-tab-${section}`} className="catalog-section-page">{data.isPlaceholderData ? <Loading text="Consultando sección…"/> : <>
      {section === 'summary' && <><div className="panel-heading"><h3>Gobierno vigente <small className="muted">· metadata editable</small></h3>{!governance.inherited && canEdit && <button className="button secondary small" onClick={() => setEditing(true)}><Pencil size={14}/> Editar gobierno</button>}</div><dl className="governance-grid">{[['Macrodominio', governance.macro_domain?.name || governance.macro_domain_name], ['Dominio', governance.domain?.name || governance.domain_name], ['Descripción funcional', governance.description || dataset.description], ['Responsable de negocio', governance.business_owner ? governance.business_owner.name + (governance.business_owner.active === false ? ' (inactivo)' : '') : governance.business_owner_id], ['Gestor', governance.steward ? governance.steward.name + (governance.steward.active === false ? ' (inactivo)' : '') : governance.steward_id], ['Custodio técnico', governance.technical_custodian ? governance.technical_custodian.name + (governance.technical_custodian.active === false ? ' (inactivo)' : '') : governance.technical_custodian_id], ['Clasificación de información', governance.information_classification && governance.information_classification !== 'UNKNOWN' ? label(governance.information_classification) : 'Sin determinar'], ['Criticidad', label(governance.criticality || dataset.criticality)], ['Origen', label(dataset.origin || dataset.source_type)], ['Área heredada', dataset.domain]].map(([title, text]) => <div key={title}><dt>{title}</dt><dd>{text || 'Sin registrar'}</dd></div>)}</dl>{governance.inherited && <Notice>Clasificación heredada de una entrada Intake mediante su relación registrada. Administra la clasificación en la fuente.</Notice>}
        <h3>Evaluación actual <small className="muted">· calculada para la versión seleccionada</small></h3><div className="eligibility-grid"><div><strong>Clasificación completa y activa</strong><Badge value={eligibility.classification_complete ? 'READY' : 'PENDING'}/></div><div><strong>Evidencia de aprobación estricta</strong><Badge value={eligibility.strict_approval?.approved ? 'APPROVED' : 'LEGACY_UNVERIFIED'}/></div><div><strong>Disponibilidad actual</strong><Badge value={eligibility.availability?.available === true ? 'AVAILABLE' : 'UNAVAILABLE'}/><small className="table-subtitle">{eligibility.availability?.verified_bytes ? 'Integridad comprobada' : 'La integridad completa se comprueba al ejecutar.'}</small></div><div><strong>Habilitación para Reportes</strong><Badge value={eligibility.eligible ? 'READY' : 'BLOCKED'}/></div></div>{(eligibility.reasons || []).map((reason: RecordData | string, index: number) => <Notice key={index}>{typeof reason === 'string' ? reason : reason.message || reason.code}</Notice>)}<DatasetBlocks datasetId={id!}/></>}
      {section === 'columns' && <><DatasetGlossary datasetId={id!} terms={value?.dataset_terms || []}/><p className="muted">Esquema registrado de la versión {value?.version_id || params.get('version_id') || 'vigente'}. La documentación funcional no modifica tipos ni reasigna columnas desaparecidas.</p><div className="table-scroll"><table><thead><tr><th>Columna</th><th>Tipo lógico</th><th>Descripción funcional</th><th>Glosario</th><th/></tr></thead><tbody>{value?.items.map(item => <tr key={item.name || item.column_name}><td className="mono">{item.name || item.column_name}</td><td>{item.logical_type || item.type}</td><td>{item.documentation?.description || item.description || 'Sin documentar'}</td><td>{(item.terms || item.documentation?.terms || []).map((term: RecordData) => term.name).join(', ') || 'Sin asociaciones'}</td><td>{canEdit && <button className="text-button" onClick={() => setColumn(item)}>Documentar columna</button>}</td></tr>)}</tbody></table></div></>}
      {section === 'versions' && <div className="table-scroll"><table><thead><tr><th>Versión</th><th>Origen</th><th>Filas</th><th>Creada</th><th/></tr></thead><tbody>{value?.items.map(item => <tr key={item.id}><td>v{item.version}</td><td>{label(item.source_type)}</td><td>{number(item.row_count)}</td><td>{date(item.created_at)}</td><td><Link to={`/datasets/${id}?version=${item.id}`}>Perfil y evidencia</Link></td></tr>)}</tbody></table></div>}
      {section === 'quality' && <div className="table-scroll"><table><thead><tr><th>Contrato / revisión</th><th>Entrada / salida</th><th>Ejecución</th><th>Aprobación estricta</th><th>Motivo</th></tr></thead><tbody>{value?.items.map(item => <tr key={item.id || item.run_id}><td><Link to={`/intake?contract_id=${item.contract_id || item.strict_approval?.contract_id || item.config_id}`}>{item.contract_name || item.strict_approval?.contract_id || item.config_id}</Link><small className="table-subtitle">Revisión {item.contract_revision_id || item.strict_approval?.contract_revision_id || item.config_id}</small></td><td>{item.input_version_id || item.dataset_version_id || item.strict_approval?.input_version_id} → {item.output_version_id || item.strict_approval?.output_version_id || 'Sin salida'}</td><td><Link to={`/runs/${item.run_id || item.id}`}><Badge value={item.decision || item.status}/></Link></td><td><Badge value={item.strict_approval?.approved || item.strict_approved === true ? 'APPROVED' : 'LEGACY_UNVERIFIED'}/></td><td>{(item.strict_approval?.reasons || item.reasons || []).map((reason: RecordData | string) => typeof reason === 'string' ? reason : reason.message || reason.code).join(' · ')}</td></tr>)}</tbody></table></div>}
      {section === 'lineage' && <><Notice>Relaciones verificables de activos, versiones y ejecuciones. Los joins y agregaciones no establecen correspondencia fila a fila.</Notice><ul className="catalog-lineage">{value?.items.map((item, index) => <li key={item.id || index}>{item.source_href ? <Link to={item.source_href}>{item.source_name || item.source_id}</Link> : <Link to={`/catalog/datasets/${item.source_dataset_id || item.parent_dataset_id}`}>{item.source_name || item.source_dataset_id || item.parent_dataset_id}</Link>} <span aria-label="relación hacia">→</span> {item.target_href ? <Link to={item.target_href}>{item.target_name || item.target_id}</Link> : <span>{item.target_name || dataset.name}</span>}<small>{label(item.relation || item.kind || item.resource_type)} · {item.source_version_id || item.input_version_id} {item.run_id && <Link to={`/runs/${item.run_id}`}>Ver ejecución</Link>}{item.report_execution_id && <Link to={`/reports/executions/${item.report_execution_id}`}>Ejecución de reporte</Link>}</small></li>)}</ul></>}
      {section === 'history' && <div className="table-scroll"><table><thead><tr><th>Instante</th><th>Acción</th><th>Actor</th><th>Gobierno registrado</th></tr></thead><tbody>{value?.items.map(item => <tr key={item.id}><td>{date(item.created_at || item.changed_at)}</td><td>{label(item.action || item.event_type || 'GOVERNANCE_UPDATED')}</td><td>{item.actor_name || item.actor_id || item.user_id}</td><td>{item.macro_domain_name || item.snapshot?.macro_domain?.name || item.snapshot?.macro_domain_name || item.macro_domain_id || 'Sin macrodominio'} / {item.domain_name || item.snapshot?.domain?.name || item.snapshot?.domain_name || item.domain_id || 'Sin dominio'}<small className="table-subtitle">Revisión {item.version || item.governance_version} · {item.reason}</small></td></tr>)}</tbody></table></div>}
      {section !== 'summary' && !value?.items.length && <Empty title="Sin registros en esta sección" description="No se inventan evidencias ni asociaciones cuando la metadata histórica es insuficiente."/>}
      </>}{section !== 'summary' && !data.isPlaceholderData && <Pagination offset={offset} total={value?.total || 0} limit={limit} onChange={value => { const next = new URLSearchParams(params); next.set('offset', String(value)); setParams(next) }}/>}</div>
    {editing && <GovernanceEditor dataset={dataset} governance={governance} onClose={() => setEditing(false)}/>}{column && <ColumnEditor datasetId={id!} column={column} versionId={column.version_id || value?.version_id || dataset.latest_version_id} onClose={() => setColumn(null)}/>}
  </section>
}

export function CatalogAdmin() {
  const cache = useQueryClient(), canDomains = usePermission('domains:manage'), canGlossary = usePermission('glossary:manage'), canReadDomains = usePermission('datasets:read'), canReadGlossary = usePermission('glossary:read')
  const [tab, setTab] = useState<'macrodomains' | 'domains' | 'glossary'>('macrodomains'), [search, setSearch] = useState(''), [offset, setOffset] = useState(0), [editing, setEditing] = useState<RecordData | null>(null), [form, setForm] = useState({ name: '', description: '', definition: '', macro_domain_id: '', active: true })
  const records = useQuery({ queryKey: ['governance-admin', tab, search, offset], queryFn: () => api<Collection>(`/governance/${tab}?search=${encodeURIComponent(search)}&offset=${offset}&limit=${limit}`), enabled: tab === 'glossary' ? canReadGlossary : canReadDomains })
  const macros = useQuery({ queryKey: ['governance-macrodomains', 'admin'], queryFn: () => api<{ items: GovernanceEntity[] }>('/governance/macrodomains?active=true&limit=200'), enabled: tab === 'domains' && canReadDomains })
  const save = useMutation({ mutationFn: () => api(`/governance/${tab}${editing?.id ? `/${editing.id}` : ''}`, { method: editing?.id ? 'PATCH' : 'POST', body: JSON.stringify({ name: form.name.trim(), ...(tab === 'glossary' ? { definition: form.definition } : { description: form.description }), ...(tab === 'domains' ? { macro_domain_id: form.macro_domain_id } : {}), ...(editing?.id ? { expected_version: editing.version, active: form.active } : {}) }) }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['governance-admin'] }); void cache.invalidateQueries({ queryKey: ['governance-macrodomains'] }); void cache.invalidateQueries({ queryKey: ['governance-domains'] }); void cache.invalidateQueries({ queryKey: ['catalog-tree'] }); setEditing(null) } })
  const canWrite = tab === 'glossary' ? canGlossary : canDomains
  function edit(item: RecordData) { setEditing(item); setForm({ name: item.name || '', description: item.description || '', definition: item.definition || '', macro_domain_id: item.macro_domain_id || '', active: item.active ?? true }); save.reset() }
  return <section className="panel catalog-admin"><h2>Dominios y glosario</h2><p className="muted">Renombrar conserva identidad e historia. Desactivar impide nuevas selecciones y la habilitación actual de Reportes.</p><div className="tabs">{([['macrodomains', 'Macrodominios'], ['domains', 'Dominios'], ['glossary', 'Glosario']] as const).map(([key, title]) => <button key={key} className={key === tab ? 'active' : ''} onClick={() => { setTab(key); setOffset(0) }}>{title}</button>)}</div><div className="table-toolbar"><SearchBox value={search} onChange={value => { setSearch(value); setOffset(0) }}/>{canWrite && <button className="button primary small" onClick={() => edit({})}><Plus size={14}/> Crear</button>}</div>{!(tab === 'glossary' ? canReadGlossary : canReadDomains) ? <Notice>Tu rol no tiene permiso para consultar esta sección.</Notice> : records.isPending ? <Loading/> : records.error ? <ErrorState error={records.error} retry={() => { void records.refetch() }}/> : <div className="table-scroll"><table><thead><tr><th>Nombre</th><th>{tab === 'glossary' ? 'Definición' : 'Descripción'}</th><th>Estado</th><th/></tr></thead><tbody>{records.data?.items.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.definition || item.description}</td><td><Badge value={item.active ? 'ACTIVE' : 'INACTIVE'}/></td><td>{canWrite && <button className="text-button" onClick={() => edit(item)}>Editar</button>}</td></tr>)}</tbody></table></div>}<Pagination offset={offset} total={records.data?.total || 0} limit={limit} onChange={setOffset}/>
    <Modal open={!!editing} onOpenChange={open => { if (!open && !save.isPending) setEditing(null) }} title={`${editing?.id ? 'Editar' : 'Crear'} ${tab === 'glossary' ? 'término' : tab === 'domains' ? 'dominio' : 'macrodominio'}`} description="Los duplicados y conflictos de revisión se validan en el servidor."><form className="form-stack" onSubmit={event => { event.preventDefault(); save.mutate() }}><Field label="Nombre"><input required maxLength={160} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })}/></Field>{tab === 'domains' && <Field label="Macrodominio"><select required disabled={!!editing?.id} value={form.macro_domain_id} onChange={event => setForm({ ...form, macro_domain_id: event.target.value })}><option value="">Selecciona un macrodominio</option>{macros.data?.items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}<Field label={tab === 'glossary' ? 'Definición' : 'Descripción'}><textarea required={tab === 'glossary'} value={tab === 'glossary' ? form.definition : form.description} onChange={event => setForm({ ...form, [tab === 'glossary' ? 'definition' : 'description']: event.target.value })}/></Field>{editing?.id && <label className="checkbox-row"><input type="checkbox" checked={form.active} onChange={event => setForm({ ...form, active: event.target.checked })}/>Activo</label>}{editing?.id && !form.active && <Notice>Al guardar la desactivación, los recursos conservan su asociación histórica y deben reclasificarse para Reportes.</Notice>}{save.error && <ErrorState error={save.error}/>}<div className="modal-footer"><button className="button secondary" type="button" disabled={save.isPending} onClick={() => setEditing(null)}>Cancelar</button><button className="button primary" disabled={save.isPending || !form.name.trim() || (tab === 'domains' && !form.macro_domain_id)}>{save.isPending ? 'Guardando…' : 'Confirmar cambios'}</button></div></form></Modal>
  </section>
}

export function CatalogRoutes() {
  return <><PageHeading eyebrow="GOBIERNO DEL DATO" title="Catálogo" description="Localiza activos autorizados e inspecciona su gobierno, evidencia y procedencia."/><div className="catalog-layout"><CatalogTree/><div className="catalog-main"><Routes><Route index element={<CatalogResources/>}/><Route path="datasets/:id" element={<CatalogDataset/>}/><Route path="admin" element={<CatalogAdmin/>}/></Routes></div></div></>
}
