import { Field } from '../../components/ui'
import type { Filter, FilterGroup, SchemaColumn } from './types'

type FilterColumn = SchemaColumn & { source_alias?: string; result_name?: string }
const operators: Record<Filter['operator'], string> = { EQ: 'Igual', NE: 'Distinto', GT: 'Mayor', GE: 'Mayor o igual', LT: 'Menor', LE: 'Menor o igual', IS_NULL: 'Es nulo', IS_NOT_NULL: 'No es nulo', IN: 'Incluido en', CONTAINS: 'Contiene', STARTS_WITH: 'Comienza por' }
function availableOperators(column?: FilterColumn): Filter['operator'][] {
  const logical = column?.logical_type || column?.type
  return (Object.keys(operators) as Filter['operator'][]).filter(operator => {
    if (['CONTAINS', 'STARTS_WITH'].includes(operator)) return logical === 'STRING'
    if (['GT', 'GE', 'LT', 'LE'].includes(operator)) return logical !== 'BOOLEAN'
    return true
  })
}
export function FilterBuilder({ value, onChange, columns, title, depth = 0 }: { value: FilterGroup; onChange: (value: FilterGroup) => void; columns: FilterColumn[]; title: string; depth?: number }) {
  function update(index: number, condition: Filter | FilterGroup) { onChange({ ...value, conditions: value.conditions.map((current, i) => i === index ? condition : current) }) }
  return <fieldset className="report-filters"><legend>{title}</legend><Field label={`${title}: combinar condiciones`}><select value={value.operator} onChange={event => onChange({ ...value, operator: event.target.value as FilterGroup['operator'] })}><option value="AND">Y · todas las condiciones</option><option value="OR">O · alguna condición</option></select></Field>
    {value.conditions.map((condition, index) => {
      if ('conditions' in condition) return <div key={index}><FilterBuilder value={condition} onChange={group => update(index, group)} columns={columns} title={`${title}, grupo ${index + 1}`} depth={depth + 1}/><button type="button" className="text-button" onClick={() => onChange({ ...value, conditions: value.conditions.filter((_, i) => i !== index) })}>Quitar grupo {index + 1}</button></div>
      const selected = columns.find(item => item.source_alias === condition.source_alias && (item.result_name || item.name) === condition.column)
      const choices = availableOperators(selected)
      return <div className="report-filter-row" key={index}><Field label={`${title}, condición ${index + 1}: columna`}><select value={`${condition.source_alias || ''}:${condition.column}`} onChange={event => { const column = columns.find(item => `${item.source_alias || ''}:${item.result_name || item.name}` === event.target.value); if (column) update(index, { ...condition, source_alias: column.source_alias, column: column.result_name || column.name, operator: availableOperators(column).includes(condition.operator) ? condition.operator : 'EQ' }) }}><option value=":">Selecciona columna</option>{columns.map(column => <option key={`${column.source_alias}:${column.name}`} value={`${column.source_alias || ''}:${column.result_name || column.name}`}>{column.source_alias ? `${column.source_alias}.` : ''}{column.result_name || column.name} · {column.logical_type || column.type}</option>)}</select></Field><Field label={`${title}, condición ${index + 1}: operador`}><select value={condition.operator} onChange={event => update(index, { ...condition, operator: event.target.value as Filter['operator'] })}>{choices.map(key => <option key={key} value={key}>{operators[key]}</option>)}</select></Field>{!['IS_NULL', 'IS_NOT_NULL'].includes(condition.operator) && <Field label={`${title}, condición ${index + 1}: valor`} hint={condition.operator === 'IN' ? 'Un valor por línea, sin normalización.' : ['CONTAINS', 'STARTS_WITH'].includes(condition.operator) ? 'Texto literal sensible a mayúsculas; %, _, comillas y barras se conservan. Vacío coincide con todo texto no nulo.' : 'Se convierte estrictamente al tipo registrado. Vacío conserva cadena vacía.'}><textarea rows={condition.operator === 'IN' ? 3 : 1} value={Array.isArray(condition.value) ? condition.value.join('\n') : String(condition.value ?? '')} onChange={event => update(index, { ...condition, value: condition.operator === 'IN' ? event.target.value.split('\n') : event.target.value })}/></Field>}<button type="button" className="text-button" aria-label={`Quitar ${title}, condición ${index + 1}`} onClick={() => onChange({ ...value, conditions: value.conditions.filter((_, i) => i !== index) })}>Quitar</button></div>
    })}
    <div className="classification-actions"><button type="button" className="text-button" disabled={!columns.length} onClick={() => onChange({ ...value, conditions: [...value.conditions, { source_alias: columns[0]?.source_alias, column: columns[0]?.result_name || columns[0]?.name || '', operator: 'EQ', value: '' }] })}>Añadir condición</button>{depth < 3 && <button type="button" className="text-button" onClick={() => onChange({ ...value, conditions: [...value.conditions, { operator: 'AND', conditions: [] }] })}>Añadir grupo Y/O</button>}</div>
  </fieldset>
}
