import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api, post } from '../../api/client'
import type { RecordData } from '../../api/client'
import { SourceLinks } from './SourceLinks'
import { usePermission } from '../../app/session'
import { Badge, date, ErrorState, label, Loading, Notice, number, PageHeading } from '../../components/ui'

export function ReportExecution({ executionId, embedded = false }: { executionId?: string; embedded?: boolean }) {
  const params = useParams(), id = executionId || params.id, cache = useQueryClient(), canGenerate = usePermission('reports:generate')
  const state = useQuery({ queryKey: ['report-execution', id], queryFn: () => api<RecordData>(`/reports/executions/${id}`), enabled: !!id, refetchInterval: query => ['SUCCESS', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'COMPLETED', 'INTERRUPTED'].includes(query.state.data?.status) ? false : 2000 })
  const cancel = useMutation({ mutationFn: () => post(`/reports/executions/${id}/cancel`), onSuccess: value => { cache.setQueryData(['report-execution', id], value); void cache.invalidateQueries({ queryKey: ['report-executions'] }) } })
  const run = state.data
  if (state.isPending) return <Loading text="Consultando ejecución de reporte…"/>
  if (state.error) return <ErrorState error={state.error} retry={() => { void state.refetch() }}/>
  if (!run) return null
  const metrics = run.metrics || {}, rows = metrics.rows ?? metrics.rows_generated ?? metrics.processed_rows ?? run.processed_rows, bytes = metrics.canonical_size_bytes ?? metrics.bytes_prepared ?? metrics.bytes ?? metrics.processed_bytes ?? run.processed_bytes, parts = metrics.parts ?? metrics.parts_prepared ?? metrics.parts_count, elapsed = metrics.elapsed_seconds ?? metrics.duration_seconds
  const measured = (value: unknown) => value == null ? '—' : number(value)
  const terminal = ['SUCCESS', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'COMPLETED', 'INTERRUPTED'].includes(run.status)
  return <>{!embedded && <PageHeading back="/reports/history" eyebrow="EJECUCIÓN DE REPORTE" title={run.name || run.id} description="Contexto de fuentes, fases, métricas y resultado registrados por el servidor."/>}<section className={embedded ? 'report-context' : 'panel report-builder-card'} aria-live="polite"><div className="panel-heading"><div><h3>{run.profile || run.action || 'DATASET'} · <Badge value={run.status}/></h3><p>{run.progress_stage || run.stage || run.phase || 'Estado registrado'} {run.progress_percent != null && `· ${number(run.progress_percent)}%`}</p></div><Link className="text-link" to={`/reports/executions/${id}`}>Enlace a la ejecución</Link></div><div className="report-status-counters"><span>{measured(rows)} filas de resultado</span><span>{measured(bytes)} {run.profile === 'DATASET' ? 'bytes canónicos preparados' : 'bytes de resultado'}</span><span>{measured(parts)} partes</span>{elapsed != null && <span>{number(elapsed)} s</span>}</div>{run.metrics?.total_rows != null && <p>Total comprobado: {number(run.metrics.total_rows)} filas.</p>}<p className="muted">Registrada {date(run.created_at)} {run.finished_at && `· Finalizada ${date(run.finished_at)}`}</p>{(run.sources || run.resolved_sources || run.context?.sources || []).map((source: RecordData, index: number) => <p key={source.alias || index}><strong>{source.alias}</strong> · entrada <Link to={`/catalog/datasets/${source.input_dataset_id}`}>{source.input_dataset_id}</Link> / {source.input_version_id} → salida {source.output_version_id} · contrato {source.contract_id} / {source.contract_revision_id} · aprobación <Link to={`/runs/${source.approval_run_id || source.run_id}`}>{source.approval_run_id || source.run_id}</Link><br/><SourceLinks source={source}/></p>)}{run.error_message && <Notice>{run.error_message} {run.error_code && <span className="mono">({run.error_code})</span>}</Notice>}{run.error?.message && <Notice>{run.error.message}</Notice>}{run.output_dataset_id && <Notice success>Dataset publicado íntegramente. Estado al publicar: Pendiente de validación de calidad. <Link to={`/datasets/${run.output_dataset_id}`}>Ver dataset</Link> · <Link to={`/catalog/datasets/${run.output_dataset_id}`}>Gobierno y linaje</Link> · <Link to={`/intake?dataset_id=${run.output_dataset_id}`}>Validar con Intake</Link></Notice>}{run.profile === 'DOWNLOAD' && <Notice>Generación: {label(run.generation_status)} · Transmisión: {label(run.transmission_status)}. El servidor no conserva el archivo y no comprueba si el navegador lo guardó.</Notice>}{!terminal && run.profile === 'DATASET' && <><p className="muted">Puedes salir de esta pantalla. El trabajo de generación continúa en el servidor.</p>{canGenerate && <button className="button secondary" disabled={cancel.isPending || run.cancel_requested} onClick={() => cancel.mutate()}>{run.cancel_requested ? 'Cancelación solicitada…' : 'Cancelar generación'}</button>}</>}{cancel.error && <ErrorState error={cancel.error}/>}</section></>
}
