import { test, expect, type Page } from '@playwright/test'
import fs from 'node:fs/promises'

test.setTimeout(240_000)

async function post(page: Page, endpoint: string, data: unknown, headers: Record<string, string>) {
  const response = await page.request.post(`/api/v1${endpoint}`, { data, headers })
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}
async function upload(page: Page, name: string, csv: string) {
  await page.goto('/datasets?upload=1')
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nombre del dataset', { exact: true }).fill(name)
  await dialog.getByLabel('Archivo', { exact: true }).setInputFiles({ name: 'report-source.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await expect(dialog.getByText(/Transferencia completa/)).toBeVisible()
  await expect(dialog.getByLabel('Macrodominio (opcional)', { exact: true })).toHaveValue('')
  await dialog.getByLabel('Identificador customer_id', { exact: true }).check()
  const responsePromise = page.waitForResponse(response => /\/datasets\/[^/]+\/acquisitions$/.test(new URL(response.url()).pathname) && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Registrar adquisición', exact: true }).click()
  const response = await responsePromise
  expect(response.status(), await response.text()).toBe(202)
  const run = await response.json()
  await expect.poll(async () => (await (await page.request.get(`/api/v1/acquisitions/${run.id}`)).json()).status, { timeout: 90_000 }).toBe('SUCCESS')
  await page.waitForURL(/\/datasets\//)
  return run.dataset_id as string
}
async function classify(page: Page, datasetId: string, macro: string, domain: string) {
  const before = await (await page.request.get(`/api/v1/datasets/${datasetId}`)).json()
  await page.goto(`/catalog/datasets/${datasetId}`)
  await page.getByRole('button', { name: 'Editar gobierno', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Macrodominio (opcional)', { exact: true }).selectOption(macro)
  await dialog.getByLabel('Dominio (opcional)', { exact: true }).selectOption(domain)
  await dialog.getByLabel('Descripción funcional', { exact: true }).fill('Fuente sintética de certificación de gobierno y Reportes.')
  await dialog.getByRole('button', { name: 'Guardar gobierno', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const after = await (await page.request.get(`/api/v1/datasets/${datasetId}`)).json()
  expect(after.versions.map((version: { id: string }) => version.id)).toEqual(before.versions.map((version: { id: string }) => version.id))
  await page.reload()
  await expect(page.getByText('Fuente sintética de certificación de gobierno y Reportes.').first()).toBeVisible()
}
async function strictIntake(page: Page, datasetId: string, name: string, required: string[], headers: Record<string, string>) {
  const dataset = await (await page.request.get(`/api/v1/datasets/${datasetId}`)).json()
  const contract = await post(page, '/intake/contracts', { name, dataset_id: datasetId, config: { required_columns: required, unique_columns: [required[0]], max_error_rate: 0 } }, headers)
  const queued = await post(page, '/intake/runs', { contract_id: contract.id, dataset_version_id: dataset.versions[0].id }, headers)
  await expect.poll(async () => (await (await page.request.get(`/api/v1/runs/${queued.id}`)).json()).status, { timeout: 90_000 }).toBe('SUCCESS')
  const run = await (await page.request.get(`/api/v1/runs/${queued.id}`)).json()
  expect(run.decision).toBe('APPROVED')
  return { contract, run }
}

test('Catálogo y Reportes: dos cargas → gobierno → Intake estricto → join → preview → descarga → dataset → nueva aprobación', async ({ page }, testInfo) => {
  const browserErrors: string[] = []; page.on('pageerror', error => browserErrors.push(error.message))
  await page.goto('/'); await page.getByRole('button', { name: 'Entrar al entorno demo', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Centro de control', exact: true })).toBeVisible()
  const me = await (await page.request.get('/api/v1/me')).json(), headers = { 'X-CSRF-Token': me.csrf_token as string }, stamp = Date.now()
  const macro = await post(page, '/governance/macrodomains', { name: `E2E gobierno ${stamp}` }, headers)
  const domain = await post(page, '/governance/domains', { name: 'Clientes', macro_domain_id: macro.id }, headers)
  const leftName = `E2E reportes ${stamp} saldos`, rightName = `E2E reportes ${stamp} segmentos`
  const left = await upload(page, leftName, 'customer_id,amount\n001,10.25\n002,20.50\n003,30.75\n')
  const right = await upload(page, rightName, 'customer_id,segment\n001,A\n002,B\n004,C\n')
  await classify(page, left, macro.id, domain.id); await classify(page, right, macro.id, domain.id)
  const approvalLeft = await strictIntake(page, left, leftName, ['customer_id', 'amount'], headers)
  const approvalRight = await strictIntake(page, right, rightName, ['customer_id', 'segment'], headers)
  await page.goto(`/catalog/datasets/${left}?section=columns`)
  await expect(page.getByRole('cell', { name: 'customer_id', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Columnas y glosario', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Versiones', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tab', { name: 'Versiones', exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByRole('tab', { name: 'Historial', exact: true })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page.getByRole('tab', { name: 'Resumen y gobierno', exact: true })).toBeFocused()
  await page.getByRole('tab', { name: 'Calidad y contratos', exact: true }).click()
  await expect(page.getByRole('link').filter({ has: page.getByText('Aprobado', { exact: true }) }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: approvalLeft.contract.id, exact: true })).toBeVisible()
  await expect(page.getByRole('cell').filter({ hasText: approvalLeft.run.dataset_version_id })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('catalog-quality.png'), fullPage: true })

  await page.goto('/reports/new')
  for (const sourceName of [leftName, rightName]) {
    await page.getByLabel('Buscar datasets y contratos…').fill(sourceName)
    const candidate = page.locator('.report-source-candidate').filter({ has: page.getByRole('link', { name: sourceName, exact: true }) })
    await expect(candidate.getByRole('button', { name: 'Añadir fuente' })).toBeEnabled()
    await candidate.getByRole('button', { name: 'Añadir fuente' }).click()
  }
  await page.getByRole('button', { name: '2. Cruces', exact: true }).click(); await page.getByRole('button', { name: 'Añadir cruce' }).click()
  await page.getByLabel('Tipo de join, cruce 1').selectOption('LEFT')
  await page.getByLabel('Llave izquierda 1, cruce 1').selectOption('customer_id'); await page.getByLabel('Llave derecha 1, cruce 1').selectOption('customer_id')
  await page.getByRole('button', { name: '3. Columnas y filtros', exact: true }).click()
  for (const name of [/fuente1.customer_id/, /fuente1.amount/, /fuente2.segment/]) await page.getByRole('checkbox', { name }).check()
  await page.getByRole('button', { name: 'Añadir columna de orden', exact: true }).click()
  await page.getByRole('button', { name: 'Resolver fuentes y validar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ejecutar vista previa', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Ejecutar vista previa', exact: true }).click()
  await expect(page.getByRole('cell', { name: '001', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: '003', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'null', exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('report-preview.png'), fullPage: true })
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Descargar reporte', exact: true }).click()
  const file = await downloadPromise; await file.saveAs(testInfo.outputPath('report-client.csv'))
  const csv = await fs.readFile(testInfo.outputPath('report-client.csv'), 'utf8')
  expect(csv).toContain('001'); expect(csv).toContain('003'); expect(csv).not.toContain('004')
  await page.getByRole('button', { name: 'Generar dataset', exact: true }).click()
  const dialog = page.getByRole('dialog'), generatedName = `E2E reportes ${stamp} resultado`
  await dialog.getByLabel('Nombre del nuevo dataset').fill(generatedName)
  await dialog.getByLabel('Macrodominio (opcional)', { exact: true }).selectOption(macro.id); await dialog.getByLabel('Dominio (opcional)', { exact: true }).selectOption(domain.id)
  const submitted = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v1/reports/datasets' && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Confirmar generación', exact: true }).click()
  const generationResponse = await submitted; expect(generationResponse.ok(), await generationResponse.text()).toBeTruthy(); const generation = await generationResponse.json()
  await expect.poll(async () => (await (await page.request.get(`/api/v1/reports/executions/${generation.id}`)).json()).status, { timeout: 90_000 }).toBe('SUCCESS')
  const published = await (await page.request.get(`/api/v1/reports/executions/${generation.id}`)).json()
  await expect(page.getByText(/Pendiente de validación de calidad/)).toBeVisible()
  await expect(page.getByText('3 filas de resultado', { exact: true })).toBeVisible()
  await expect(page.getByText('1 partes', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Gobierno y linaje', exact: true }).click()
  await expect(page.getByRole('heading', { name: generatedName, exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Linaje', exact: true }).click(); await expect(page.locator('.catalog-lineage li').first()).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('report-lineage.png'), fullPage: true })
  await page.goto(`/reports/executions/${generation.id}`); await page.getByRole('link', { name: 'Validar con Intake', exact: true }).click()
  await expect(page.getByText(/Dataset seleccionado para validar/)).toBeVisible(); await page.getByRole('button', { name: 'Nuevo contrato', exact: true }).first().click()
  await expect(page.getByRole('dialog').getByLabel('Dataset', { exact: true })).toHaveValue(published.output_dataset_id)
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar', exact: true }).click()
  const derivedApproval = await strictIntake(page, published.output_dataset_id, generatedName, ['fuente1_customer_id'], headers)
  const followUpDraft = { mode: 'SQL', sources: [{ alias: 'resultado', input_dataset_id: published.output_dataset_id, contract_id: derivedApproval.contract.id, contract_revision_ids: [derivedApproval.contract.id], policy: 'LATEST_APPROVED' }], joins: [], columns: [], order_by: [], sql: 'SELECT resultado.fuente1_customer_id AS id FROM resultado ORDER BY resultado.fuente1_customer_id', parameters: [], source_filters: {}, expected_schemas: {}, output_preferences: { format: 'XLSX' } }
  const followUp = await post(page, '/reports/resolve', { draft: followUpDraft }, headers)
  const finalPreview = await post(page, '/reports/preview', { context_id: followUp.context_id }, headers)
  expect(finalPreview.rows.map((row: { id: string }) => row.id)).toEqual(['001', '002', '003'])
  const saved = await post(page, '/reports/definitions', { name: `E2E historia ${stamp}`, draft: followUpDraft }, headers)
  const revisionId = saved.revisions[0].id
  await post(page, `/reports/definitions/${saved.id}/revisions`, { expected_version: saved.version, draft: { ...followUpDraft, output_preferences: { format: 'CSV' } } }, headers)
  await page.goto(`/reports/definitions/${saved.id}?revision_id=${revisionId}`)
  await expect(page.getByRole('heading', { name: `E2E historia ${stamp} · revisión 1`, exact: true })).toBeVisible()
  await expect(page.getByText(/La revisión vigente es 2/)).toBeVisible()
  const historicalResolve = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v1/reports/resolve' && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Resolver fuentes y validar', exact: true }).click()
  const historicalResponse = await historicalResolve
  expect(historicalResponse.ok(), await historicalResponse.text()).toBeTruthy()
  expect(historicalResponse.request().postDataJSON().revision_id).toBe(revisionId)
  await expect(page.getByLabel('Formato de descarga', { exact: true })).toHaveValue('XLSX')
  await page.getByRole('button', { name: 'Ejecutar vista previa', exact: true }).click()
  await expect(page.getByRole('cell', { name: '001', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Guardar definición', exact: true }).click()
  const newRevision = page.waitForResponse(response => new URL(response.url()).pathname === `/api/v1/reports/definitions/${saved.id}/revisions` && response.request().method() === 'POST')
  await page.getByRole('dialog').getByRole('button', { name: 'Guardar definición', exact: true }).click()
  const savedResponse = await newRevision
  expect(savedResponse.ok(), await savedResponse.text()).toBeTruthy()
  expect(savedResponse.request().postDataJSON().expected_version).toBe(2)
  await expect(page.getByRole('heading', { name: `E2E historia ${stamp} · revisión 3`, exact: true })).toBeVisible()
  expect((await savedResponse.json()).revisions[0].draft.output_preferences.format).toBe('XLSX')
  expect(browserErrors).toEqual([])
  await fs.writeFile(testInfo.outputPath('catalog-reports-cycle.json'), JSON.stringify({ left, right, approvals: [approvalLeft.run.id, approvalRight.run.id, derivedApproval.run.id], generation: generation.id, output_dataset: published.output_dataset_id, final_rows: finalPreview.rows.length }, null, 2))
})
